Added connection check.

diff --git a/bin/heritrix_job b/bin/heritrix_job
--- a/bin/heritrix_job
+++ b/bin/heritrix_job
@@ -15,7 +15,7 @@ HERITRIX_PORT="8443"
 
 usage()
 {
-		echo -ne "Submit a job to Heritrix. e.g.\n\n\theritrix_job -p daily -s /tmp/seeds.txt -n daily-1200\n\n"
+		echo -ne "Submit a job to Heritrix. e.g.\n\n\theritrix_job -p profile-daily.cxml -s /tmp/seeds.txt -n daily-1200\n\n"
 		echo "OPTIONS:"
 		echo "  -h	Show this message."
 		echo "  -p	Profile to use."
@@ -78,6 +78,13 @@ then
 	exit 1
 else
 	log "Received $(wc -l < "$SEED_PATH") seed(s) from ACT."
+fi
+
+#Check we can actually connect to Heritrix
+if [[ ! $(heritrix "none") ]]
+then
+	log "Cannot connect to https://$HERITRIX_HOST:$HERITRIX_PORT/!" >&2
+	exit 1
 fi
 
 #Kill any current jobs with the same job name.
